global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'back-end'
    static_configs:
      - targets: ['back-end:3000']
  - job_name: 'db'
    static_configs:
      - targets: ['postgres_exporter:9187']